#Tokenization

In [ ]:
import nltk
nltk.download('punkt_tab')

from nltk.tokenize import sent_tokenize

text = (
    "Natural Language Processing (NLP) is a subfield of Artificial Intelligence." +
    " Machine learning and deep learning to process text and speech." +
    " NLP is widely used in applications like chatbots, voice." +
    " NLP faces challenges such as handling ambiguous language, biases." +
    " Analyzing medical records and research papers to assist in diagnosis."
)
text = text.lower()
sentences = sent_tokenize(text)
sentences

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

['natural language processing (nlp) is a subfield of artificial intelligence.',
 'machine learning and deep learning to process text and speech.',
 'nlp is widely used in applications like chatbots, voice.',
 'nlp faces challenges such as handling ambiguous language, biases.',
 'analyzing medical records and research papers to assist in diagnosis.']

In [ ]:
from nltk.tokenize import word_tokenize
words=word_tokenize(text)
print(words)

['natural', 'language', 'processing', '(', 'nlp', ')', 'is', 'a', 'subfield', 'of', 'artificial', 'intelligence', '.', 'machine', 'learning', 'and', 'deep', 'learning', 'to', 'process', 'text', 'and', 'speech', '.', 'nlp', 'is', 'widely', 'used', 'in', 'applications', 'like', 'chatbots', ',', 'voice', '.', 'nlp', 'faces', 'challenges', 'such', 'as', 'handling', 'ambiguous', 'language', ',', 'biases', '.', 'analyzing', 'medical', 'records', 'and', 'research', 'papers', 'to', 'assist', 'in', 'diagnosis', '.']

# stopwords removal

In [ ]:
from nltk.corpus import stopwords
nltk.download("stopwords")

stop_words=set(stopwords.words("english"))
print(stopwords)

<WordListCorpusReader in '/root/nltk_data/corpora/stopwords'>

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [ ]:
filtered_words=[]
for word in words:
    if word.lower() not in stop_words:
        filtered_words.append(word)
filtered_words

['natural',
 'language',
 'processing',
 '(',
 'nlp',
 ')',
 'subfield',
 'artificial',
 'intelligence',
 '.',
 'machine',
 'learning',
 'deep',
 'learning',
 'process',
 'text',
 'speech',
 '.',
 'nlp',
 'widely',
 'used',
 'applications',
 'like',
 'chatbots',
 ',',
 'voice',
 '.',
 'nlp',
 'faces',
 'challenges',
 'handling',
 'ambiguous',
 'language',
 ',',
 'biases',
 '.',
 'analyzing',
 'medical',
 'records',
 'research',
 'papers',
 'assist',
 'diagnosis',
 '.']

In [ ]:
import nltk
nltk.download("wordnet")

[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [ ]:
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet

Lemmatizer = WordNetLemmatizer()

words=(text)

print("Word Lemmatizer (default - noun) : ")
for word in words:
  print(f"{word:15}-> {Lemmatizer.lemmatize(word)}")

Word Lemmatizer (default - noun) :
n              -> n
a              -> a
t              -> t
u              -> u
r              -> r
a              -> a
l              -> l
               ->
l              -> l
a              -> a
n              -> n
g              -> g
u              -> u
a              -> a
g              -> g
e              -> e
               ->
p              -> p
r              -> r
o              -> o
c              -> c
e              -> e
s              -> s
s              -> s
i              -> i
n              -> n
g              -> g
               ->
(              -> (
n              -> n
l              -> l
p              -> p
)              -> )
               ->
i              -> i
s              -> s
               ->
a              -> a
               ->
s              -> s
u              -> u
b              -> b
f              -> f
i              -> i
e              -> e
l              -> l
d              -> d
               ->
o              -> o
f              -> f
               ->
a              -> a
r              -> r
t              -> t
i              -> i
f              -> f
i              -> i
c              -> c
i              -> i
a              -> a
l              -> l
               ->
i              -> i
n              -> n
t              -> t
e              -> e
l              -> l
l              -> l
i              -> i
g              -> g
e              -> e
n              -> n
c              -> c
e              -> e
.              -> .
               ->
m              -> m
a              -> a
c              -> c
h              -> h
i              -> i
n              -> n
e              -> e
               ->
l              -> l
e              -> e
a              -> a
r              -> r
n              -> n
i              -> i
n              -> n
g              -> g
               ->
a              -> a
n              -> n
d              -> d
               ->
d              -> d
e              -> e
e              -> e
p              -> p
               ->
l              -> l
e              -> e
a              -> a
r              -> r
n              -> n
i              -> i
n              -> n
g              -> g
               ->
t              -> t
o              -> o
               ->
p              -> p
r              -> r
o              -> o
c              -> c
e              -> e
s              -> s
s              -> s
               ->
t              -> t
e              -> e
x              -> x
t              -> t
               ->
a              -> a
n              -> n
d              -> d
               ->
s              -> s
p              -> p
e              -> e
e              -> e
c              -> c
h              -> h
.              -> .
               ->
n              -> n
l              -> l
p              -> p
               ->
i              -> i
s              -> s
               ->
w              -> w
i              -> i
d              -> d
e              -> e
l              -> l
y              -> y
               ->
u              -> u
s              -> s
e              -> e
d              -> d
               ->
i              -> i
n              -> n
               ->
a              -> a
p              -> p
p              -> p
l              -> l
i              -> i
c              -> c
a              -> a
t              -> t
i              -> i
o              -> o
n              -> n
s              -> s
               ->
l              -> l
i              -> i
k              -> k
e              -> e
               ->
c              -> c
h              -> h
a              -> a
t              -> t
b              -> b
o              -> o
t              -> t
s              -> s
,              -> ,
               ->
v              -> v
o              -> o
i              -> i
c              -> c
e              -> e
.              -> .
               ->
n              -> n
l              -> l
p              -> p
               ->
f              -> f
a              -> a
c              -> c
e              -> e
s              -> s
               ->
c              -> c
h              -> h
a              -> a
l              -> l
l              -> l
e              -> e
n              -> n
g              -> g
e              -> e
s              -> s
               ->
s              -> s
u              -> u
c              -> c
h              -> h
               ->
a              -> a
s              -> s
               ->
h              -> h
a              -> a
n              -> n
d              -> d
l              -> l
i              -> i
n              -> n
g              -> g
               ->
a              -> a
m              -> m
b              -> b
i              -> i
g              -> g
u              -> u
o              -> o
u              -> u
s              -> s
               ->
l              -> l
a              -> a
n              -> n
g              -> g
u              -> u
a              -> a
g              -> g
e              -> e
,              -> ,
               ->
b              -> b
i              -> i
a              -> a
s              -> s
e              -> e
s              -> s
.              -> .
               ->
a              -> a
n              -> n
a              -> a
l              -> l
y              -> y
z              -> z
i              -> i
n              -> n
g              -> g
               ->
m              -> m
e              -> e
d              -> d
i              -> i
c              -> c
a              -> a
l              -> l
               ->
r              -> r
e              -> e
c              -> c
o              -> o
r              -> r
d              -> d
s              -> s
               ->
a              -> a
n              -> n
d              -> d
               ->
r              -> r
e              -> e
s              -> s
e              -> e
a              -> a
r              -> r
c              -> c
h              -> h
               ->
p              -> p
a              -> a
p              -> p
e              -> e
r              -> r
s              -> s
               ->
t              -> t
o              -> o
               ->
a              -> a
s              -> s
s              -> s
i              -> i
s              -> s
t              -> t
               ->
i              -> i
n              -> n
               ->
d              -> d
i              -> i
a              -> a
g              -> g
n              -> n
o              -> o
s              -> s
i              -> i
s              -> s
.              -> .

In [ ]:
import numpy as np

In [ ]:
filtered_words_array = np.array(filtered_words)
print("Filtered words as a NumPy array:")
print(filtered_words_array)

Filtered words as a NumPy array:
['natural' 'language' 'processing' '(' 'nlp' ')' 'subfield' 'artificial'
 'intelligence' '.' 'machine' 'learning' 'deep' 'learning' 'process'
 'text' 'speech' '.' 'nlp' 'widely' 'used' 'applications' 'like'
 'chatbots' ',' 'voice' '.' 'nlp' 'faces' 'challenges' 'handling'
 'ambiguous' 'language' ',' 'biases' '.' 'analyzing' 'medical' 'records'
 'research' 'papers' 'assist' 'diagnosis' '.']

#cleaning

In [ ]:
import re
stell = " ".join(filtered_words_array)
clean_text=re.sub(r'[^a-zA-Z0-9\s]', '', stell).strip()
clean_text

'natural language processing  nlp  subfield artificial intelligence  machine learning deep learning process text speech  nlp widely used applications like chatbots  voice  nlp faces challenges handling ambiguous language  biases  analyzing medical records research papers assist diagnosis'

#Bow

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
doc=(text)
doc

'natural language processing (nlp) is a subfield of artificial intelligence. machine learning and deep learning to process text and speech. nlp is widely used in applications like chatbots, voice. nlp faces challenges such as handling ambiguous language, biases. analyzing medical records and research papers to assist in diagnosis.'

In [ ]:
bow = CountVectorizer()
X_bow = bow.fit_transform([clean_text])
X_bow

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 31 stored elements and shape (1, 31)>

In [ ]:
bow = CountVectorizer()
X_bow = bow.fit_transform([clean_text])
data=X_bow.toarray()
print(data)

[[1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 1 1 1 1 3 1 1 1 1 1 1 1 1 1 1 1]]

In [ ]:
features=bow.get_feature_names_out()
print(features)

['ambiguous' 'analyzing' 'applications' 'artificial' 'assist' 'biases'
 'challenges' 'chatbots' 'deep' 'diagnosis' 'faces' 'handling'
 'intelligence' 'language' 'learning' 'like' 'machine' 'medical' 'natural'
 'nlp' 'papers' 'process' 'processing' 'records' 'research' 'speech'
 'subfield' 'text' 'used' 'voice' 'widely']

In [ ]:
import pandas as pd
df=pd.DataFrame(data, columns=[features])
df

,ambiguous,analyzing,applications,artificial,assist,biases,challenges,chatbots,deep,diagnosis,...,process,processing,records,research,speech,subfield,text,used,voice,widely
0,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1

#TF_IDF

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf_ve=TfidfVectorizer()
to_vector=tf_ve.fit_transform([clean_text])
tf_data=to_vector.toarray()
print(tf_data)

[[0.1490712 0.1490712 0.1490712 0.1490712 0.1490712 0.1490712 0.1490712
  0.1490712 0.1490712 0.1490712 0.1490712 0.1490712 0.1490712 0.2981424
  0.2981424 0.1490712 0.1490712 0.1490712 0.1490712 0.4472136 0.1490712
  0.1490712 0.1490712 0.1490712 0.1490712 0.1490712 0.1490712 0.1490712
  0.1490712 0.1490712 0.1490712]]

In [ ]:
tf_feature=tf_ve.get_feature_names_out()
print(tf_feature)

['ambiguous' 'analyzing' 'applications' 'artificial' 'assist' 'biases'
 'challenges' 'chatbots' 'deep' 'diagnosis' 'faces' 'handling'
 'intelligence' 'language' 'learning' 'like' 'machine' 'medical' 'natural'
 'nlp' 'papers' 'process' 'processing' 'records' 'research' 'speech'
 'subfield' 'text' 'used' 'voice' 'widely']

In [ ]:
tf_df=pd.DataFrame(tf_data,columns=[tf_feature])
tf_df

,ambiguous,analyzing,applications,artificial,assist,biases,challenges,chatbots,deep,diagnosis,...,process,processing,records,research,speech,subfield,text,used,voice,widely
0,0.149071,0.149071,0.149071,0.149071,0.149071,0.149071,0.149071,0.149071,0.149071,0.149071,...,0.149071,0.149071,0.149071,0.149071,0.149071,0.149071,0.149071,0.149071,0.149071,0.149071

# output

In [ ]:
print("BOW OUTPUT::\n\n\n",df,"\n")

print("TF_IDF OUTPUT::\n\n\n",tf_df,"\n")

BOW OUTPUT::


   ambiguous analyzing applications artificial assist biases challenges  \
0         1         1            1          1      1      1          1

  chatbots deep diagnosis  ... process processing records research speech  \
0        1    1         1  ...       1          1       1        1      1

  subfield text used voice widely
0        1    1    1     1      1

[1 rows x 31 columns]

TF_IDF OUTPUT::


   ambiguous analyzing applications artificial    assist    biases challenges  \
0  0.149071  0.149071     0.149071   0.149071  0.149071  0.149071   0.149071

   chatbots      deep diagnosis  ...   process processing   records  research  \
0  0.149071  0.149071  0.149071  ...  0.149071   0.149071  0.149071  0.149071

     speech  subfield      text      used     voice    widely
0  0.149071  0.149071  0.149071  0.149071  0.149071  0.149071

[1 rows x 31 columns]