In [ ]:
import pandas as pd

**Read the housing dataset file**

In [ ]:
data = pd.read_csv('/content/Housing_Dataset.csv')
data.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2.0,h,NaN,SS,Jellis,3/09/2016,2.5,3067.0,...,1.0,1.0,126.0,NaN,NaN,Yarra City Council,-37.8014,144.9958,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2.0,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra City Council,-37.7996,144.9984,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,2.0,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra City Council,-37.8079,144.9934,Northern Metropolitan,4019.0
3,Abbotsford,18/659 Victoria St,3.0,u,NaN,VB,Rounds,4/02/2016,2.5,3067.0,...,2.0,1.0,0.0,NaN,NaN,Yarra City Council,-37.8114,145.0116,Northern Metropolitan,4019.0
4,Abbotsford,5 Charles St,3.0,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra City Council,-37.8093,144.9944,Northern Metropolitan,4019.0

In [ ]:
data.shape

(29067, 21)

**Number of nan values in the given dataset**

In [ ]:
data.isnull().sum()

Suburb               0
Address              0
Rooms                0
Type                 0
Price             6330
Method               0
SellerG              0
Date                 0
Distance             0
Postcode             0
Bedroom2          6512
Bathroom          6518
Car               6816
Landsize          9488
BuildingArea     17295
YearBuilt        15644
CouncilArea          2
Lattitude         6301
Longtitude        6301
Regionname           2
Propertycount        2
dtype: int64

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29067 entries, 0 to 29066
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         29067 non-null  object
 1   Address        29067 non-null  object
 2   Rooms          29067 non-null  int64
 3   Type           29067 non-null  object
 4   Price          22737 non-null  float64
 5   Method         29067 non-null  object
 6   SellerG        29067 non-null  object
 7   Date           29067 non-null  object
 8   Distance       29067 non-null  float64
 9   Postcode       29067 non-null  int64
 10  Bedroom2       22555 non-null  float64
 11  Bathroom       22549 non-null  float64
 12  Car            22251 non-null  float64
 13  Landsize       19579 non-null  float64
 14  BuildingArea   11772 non-null  float64
 15  YearBuilt      13423 non-null  float64
 16  CouncilArea    29065 non-null  object
 17  Lattitude      22766 non-null  float64
 18  Longtitude     22766 non-null  float64
 19  Regionname     29065 non-null  object
 20  Propertycount  29065 non-null  float64
dtypes: float64(11), int64(2), object(8)
memory usage: 4.7+ MB

In [ ]:
usefulCols = ['Suburb', 'Rooms', 'Type', 'Method', 'SellerG', 'Regionname', 'Propertycount', 'Distance', 'CouncilArea', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'Price']

newData = data[usefulCols]

In [ ]:
newData.head()

,Suburb,Rooms,Type,Method,SellerG,Regionname,Propertycount,Distance,CouncilArea,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Price
0,Abbotsford,2.0,h,SS,Jellis,Northern Metropolitan,4019.0,2.5,Yarra City Council,2.0,1.0,1.0,126.0,NaN,NaN
1,Abbotsford,2.0,h,S,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,2.0,1.0,1.0,202.0,NaN,1480000.0
2,Abbotsford,2.0,h,S,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,2.0,1.0,0.0,156.0,79.0,1035000.0
3,Abbotsford,3.0,u,VB,Rounds,Northern Metropolitan,4019.0,2.5,Yarra City Council,3.0,2.0,1.0,0.0,NaN,NaN
4,Abbotsford,3.0,h,SP,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,3.0,2.0,0.0,134.0,150.0,1465000.0

In [ ]:
newData.shape

(14523, 15)

In [ ]:
newData.isnull().sum()

Suburb              0
Rooms               1
Type                1
Method              1
SellerG             1
Regionname          1
Propertycount       1
Distance            1
CouncilArea         1
Bedroom2         3099
Bathroom         3099
Car              3099
Landsize         3116
BuildingArea     8254
Price            3214
dtype: int64

In [ ]:
cols_fill_zero = ['Propertycount', 'Distance', 'Bedroom2', 'Bathroom', 'Car']
newData[cols_fill_zero] = newData[cols_fill_zero].fillna(0)

/tmp/ipython-input-3698509413.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newData[cols_fill_zero] = newData[cols_fill_zero].fillna(0)

In [ ]:
newData.isnull().sum()

Suburb              0
Rooms               1
Type                1
Method              1
SellerG             1
Regionname          1
Propertycount       0
Distance            0
CouncilArea         1
Bedroom2            0
Bathroom            0
Car                 0
Landsize         3116
BuildingArea     8254
Price            3214
dtype: int64

In [ ]:
newData['Landsize']=newData['Landsize'].fillna(newData['Landsize'].median())
newData['BuildingArea'] = newData['BuildingArea'].fillna(newData['BuildingArea'].median())

/tmp/ipython-input-4026423236.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newData['Landsize']=newData['Landsize'].fillna(newData['Landsize'].median())
/tmp/ipython-input-4026423236.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newData['BuildingArea'] = newData['BuildingArea'].fillna(newData['BuildingArea'].median())

In [ ]:
newData.isnull().sum()

Suburb              0
Rooms               1
Type                1
Method              1
SellerG             1
Regionname          1
Propertycount       0
Distance            0
CouncilArea         1
Bedroom2            0
Bathroom            0
Car                 0
Landsize            0
BuildingArea        0
Price            3214
dtype: int64

In [ ]:
newData.dropna(inplace=True)
newData.isnull().sum()

/tmp/ipython-input-2141412743.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newData.dropna(inplace=True)

Suburb           0
Rooms            0
Type             0
Method           0
SellerG          0
Regionname       0
Propertycount    0
Distance         0
CouncilArea      0
Bedroom2         0
Bathroom         0
Car              0
Landsize         0
BuildingArea     0
Price            0
dtype: int64

In [ ]:
newData.head()

,Suburb,Rooms,Type,Method,SellerG,Regionname,Propertycount,Distance,CouncilArea,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Price
1,Abbotsford,2.0,h,S,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,2.0,1.0,1.0,202.0,125.0,1480000.0
2,Abbotsford,2.0,h,S,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,2.0,1.0,0.0,156.0,79.0,1035000.0
4,Abbotsford,3.0,h,SP,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,3.0,2.0,0.0,134.0,150.0,1465000.0
5,Abbotsford,3.0,h,PI,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,3.0,2.0,1.0,94.0,125.0,850000.0
6,Abbotsford,4.0,h,VB,Nelson,Northern Metropolitan,4019.0,2.5,Yarra City Council,3.0,1.0,2.0,120.0,142.0,1600000.0

In [ ]:
newData['Suburb'].value_counts()

Suburb
Reservoir         385
Bentleigh East    275
Richmond          245
Preston           228
Brunswick         198
                 ...
Keilor Lodge        1
MacLeod             1
Lynbrook            1
Melton South        1
Mentone             1
Name: count, Length: 209, dtype: int64

In [ ]:
newData.shape

(11309, 15)

In [ ]:
newData=pd.get_dummies(newData,drop_first=True)

In [ ]:
newData.shape

(11309, 477)

In [ ]:
## X - input features
## y - target feature
X = newData.drop(columns='Price', axis=1)
y = newData['Price']

**Splitting the data into train and test set**

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,random_state=2)

**Data Modeling - Linear Regression**

In [ ]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

**Problem of Overfitting**

In [ ]:
model.score(X_test, y_test)

0.65483737783987

In [ ]:
model.score(X_train, y_train)

0.6812344714688203

In [ ]:
model.coef_
model.intercept_

np.float64(664054.9963140137)

**Regularization Method : Lasso Regularization(L1)**

In [ ]:
from sklearn.linear_model import Lasso
lassoModel = Lasso(alpha=100, max_iter=1000, tol=.1)
lassoModel.fit(X_train, y_train)

Lasso(alpha=100, tol=0.1)

In [ ]:
lassoModel.score(X_test, y_test)

0.6595457477527874

In [ ]:
lassoModel.score(X_train, y_train)

0.6738521859186916

In [ ]:
lassoModel.coef_

In [ ]:

zero_coeff_features = X_train.columns[lassoModel.coef_ == 0]

print("Features with coefficients converted to 0 by Lasso Regularization:")
for feature in zero_coeff_features:
    print(feature,end="  | ")

Features with coefficients converted to 0 by Lasso Regularization:
Suburb_Albanvale  | Suburb_Ardeer  | Suburb_Ashwood  | Suburb_Aspendale  | Suburb_Aspendale Gardens  | Suburb_Attwood  | Suburb_Bacchus Marsh  | Suburb_Balaclava  | Suburb_Bayswater North  | Suburb_Beaconsfield  | Suburb_Beaconsfield Upper  | Suburb_Blackburn North  | Suburb_Blackburn South  | Suburb_Boronia  | Suburb_Botanic Ridge  | Suburb_Briar Hill  | Suburb_Brighton East  | Suburb_Broadmeadows  | Suburb_Brookfield  | Suburb_Brunswick West  | Suburb_Bulla  | Suburb_Bullengarook  | Suburb_Burnley  | Suburb_Burnside  | Suburb_Burnside Heights  | Suburb_Burwood  | Suburb_Burwood East  | Suburb_Cairnlea  | Suburb_Campbellfield  | Suburb_Carlton  | Suburb_Carnegie  | Suburb_Caroline Springs  | Suburb_Caulfield East  | Suburb_Chelsea Heights  | Suburb_Chirnside Park  | Suburb_Clayton  | Suburb_Clyde North  | Suburb_Coldstream  | Suburb_Collingwood  | Suburb_Coolaroo  | Suburb_Cranbourne  | Suburb_Cranbourne East  | Suburb_Cranbourne North  | Suburb_Cranbourne West  | Suburb_Cremorne  | Suburb_Croydon  | Suburb_Croydon Hills  | Suburb_Croydon North  | Suburb_Croydon South  | Suburb_Dandenong  | Suburb_Darley  | Suburb_Deepdene  | Suburb_Delahey  | Suburb_Derrimut  | Suburb_Diamond Creek  | Suburb_Diggers Rest  | Suburb_Docklands  | Suburb_Doncaster  | Suburb_Doveton  | Suburb_Emerald  | Suburb_Epping  | Suburb_Essendon West  | Suburb_Eumemmerring  | Suburb_Eynesbury  | Suburb_Footscray  | Suburb_Frankston North  | Suburb_Gardenvale  | Suburb_Gisborne  | Suburb_Gisborne South  | Suburb_Glen Huntly  | Suburb_Greensborough  | Suburb_Hallam  | Suburb_Hampton Park  | Suburb_Healesville  | Suburb_Heatherton  | Suburb_Heathmont  | Suburb_Hillside  | Suburb_Hoppers Crossing  | Suburb_Huntingdale  | Suburb_Hurstbridge  | Suburb_Jacana  | Suburb_Keilor Downs  | Suburb_Keilor Lodge  | Suburb_Keilor Park  | Suburb_Kew  | Suburb_Keysborough  | Suburb_Kilsyth  | Suburb_Kings Park  | Suburb_Kingsbury  | Suburb_Knoxfield  | Suburb_Kooyong  | Suburb_Kurunjang  | Suburb_Lalor  | Suburb_Langwarrin  | Suburb_Laverton  | Suburb_Lilydale  | Suburb_Lower Plenty  | Suburb_Lynbrook  | Suburb_Maribyrnong  | Suburb_Meadow Heights  | Suburb_Melton  | Suburb_Melton South  | Suburb_Melton West  | Suburb_Mernda  | Suburb_Mickleham  | Suburb_Mill Park  | Suburb_Monbulk  | Suburb_Montrose  | Suburb_Mount Evelyn  | Suburb_Mulgrave  | Suburb_Narre Warren  | Suburb_New Gisborne  | Suburb_Newport  | Suburb_Noble Park  | Suburb_North Warrandyte  | Suburb_Notting Hill  | Suburb_Nunawading  | Suburb_Oak Park  | Suburb_Oakleigh East  | Suburb_Officer  | Suburb_Pakenham  | Suburb_Patterson Lakes  | Suburb_Plenty  | Suburb_Plumpton  | Suburb_Research  | Suburb_Richmond  | Suburb_Riddells Creek  | Suburb_Ringwood East  | Suburb_Ripponlea  | Suburb_Rockbank  | Suburb_Rowville  | Suburb_Sandhurst  | Suburb_Scoresby  | Suburb_Seabrook  | Suburb_Seaford  | Suburb_Seaholme  | Suburb_Silvan  | Suburb_Skye  | Suburb_South Kingsville  | Suburb_Spotswood  | Suburb_Springvale  | Suburb_Springvale South  | Suburb_St Helena  | Suburb_Strathmore  | Suburb_Sunshine North  | Suburb_Sydenham  | Suburb_Tarneit  | Suburb_Taylors Hill  | Suburb_Taylors Lakes  | Suburb_Tecoma  | Suburb_The Basin  | Suburb_Travancore  | Suburb_Truganina  | Suburb_Upwey  | Suburb_Vermont  | Suburb_Vermont South  | Suburb_Wallan  | Suburb_Warrandyte  | Suburb_Warranwood  | Suburb_Waterways  | Suburb_Watsonia  | Suburb_Watsonia North  | Suburb_Wattle Glen  | Suburb_Werribee South  | Suburb_West Melbourne  | Suburb_Westmeadows  | Suburb_Whittlesea  | Suburb_Wildwood  | Suburb_Williams Landing  | Suburb_Williamstown North  | Suburb_Wollert  | Suburb_Wonga Park  | Suburb_Yarra Glen  | Suburb_croydon  | Suburb_viewbank  | SellerG_AIME  | SellerG_ASL  | SellerG_Ace  | SellerG_Airport  | SellerG_Alex  | SellerG_Alexkarbon  | SellerG_Allan  | SellerG_Allens  | SellerG_Anderson  | SellerG_Appleby  | SellerG_Aquire  | SellerG_Area  | SellerG_Ascend  | SellerG_Ash  | SellerG_Asset  | SellerG_Assisi  | SellerG_Aumeca  | SellerG_Australian  | SellerG_Avion  | SellerG_Batty  | SellerG_Bayside  | SellerG_Bekdon  | SellerG_Beller  | SellerG_Bells  | SellerG_Benchmark  | SellerG_Besser  | SellerG_Better  | SellerG_Biggin  | SellerG_Black  | SellerG_Blackbird  | SellerG_Blue  | SellerG_Bombay  | SellerG_Boran  | SellerG_Boutique  | SellerG_Bowman  | SellerG_Brace  | SellerG_Branon  | SellerG_Buckingham  | SellerG_Bullen  | SellerG_Bustin  | SellerG_Buxton/Advantage  | SellerG_Buxton/Find  | SellerG_CASTRAN  | SellerG_Calder  | SellerG_Cayzer  | SellerG_Century  | SellerG_Chambers  | SellerG_Changing  | SellerG_Charlton  | SellerG_Charter  | SellerG_Christopher  | SellerG_Clairmont  | SellerG_Collings  | SellerG_Community  | SellerG_Compton  | SellerG_Conquest  | SellerG_Coventry  | SellerG_Craig  | SellerG_Crane  | SellerG_D'Aprano  | SellerG_Daniel  | SellerG_Darras  | SellerG_David  | SellerG_Del  | SellerG_Direct  | SellerG_Dixon  | SellerG_Donovan  | SellerG_Edward  | SellerG_Elite  | SellerG_Eric  | SellerG_FN  | SellerG_First  | SellerG_Flannagan  | SellerG_Fletchers  | SellerG_Fletchers/Fletchers  | SellerG_Fletchers/One  | SellerG_Follett  | SellerG_For  | SellerG_Frank  | SellerG_Free  | SellerG_GL  | SellerG_Galldon  | SellerG_Gardiner  | SellerG_Garvey  | SellerG_Gellibrand  | SellerG_Geoff  | SellerG_Grantham  | SellerG_Gunn&Co  | SellerG_H  | SellerG_Ham  | SellerG_Hamilton  | SellerG_Harcourts  | SellerG_Hayeswinckle  | SellerG_Holland  | SellerG_Home  | SellerG_Homes  | SellerG_Hooper  | SellerG_Hoskins  | SellerG_Hunter  | SellerG_Icon  | SellerG_Iconek  | SellerG_J  | SellerG_JMRE  | SellerG_JRW  | SellerG_JY  | SellerG_Jason  | SellerG_Jim  | SellerG_Joe  | SellerG_Johnston  | SellerG_Joseph  | SellerG_Just  | SellerG_Justin  | SellerG_Karen  | SellerG_Kaye  | SellerG_Keatings  | SellerG_Ken  | SellerG_L  | SellerG_LJ  | SellerG_LJH  | SellerG_Langwell  | SellerG_Le  | SellerG_Leaders  | SellerG_Leading  | SellerG_Leased  | SellerG_Leeburn  | SellerG_Leyton  | SellerG_Lucas  | SellerG_Luxe  | SellerG_Luxton  | SellerG_M.J  | SellerG_MJ  | SellerG_Maddison  | SellerG_Maitland  | SellerG_Mandy  | SellerG_Mark  | SellerG_Mason  | SellerG_Matthew  | SellerG_Max  | SellerG_McEwing  | SellerG_McLennan  | SellerG_McNaughton  | SellerG_Meadows  | SellerG_Meallin  | SellerG_Melbourne  | SellerG_Metro  | SellerG_Millership  | SellerG_Mindacom  | SellerG_Mitchell  | SellerG_Moonee  | SellerG_Morrison  | SellerG_Munn  | SellerG_Naison  | SellerG_Nardella  | SellerG_New  | SellerG_Nguyen  | SellerG_Nicholas  | SellerG_Nicholls  | SellerG_Nicholson  | SellerG_North  | SellerG_O'Brien  | SellerG_OBrien  | SellerG_Oak  | SellerG_Obrien  | SellerG_One  | SellerG_Only  | SellerG_Open  | SellerG_Oriental  | SellerG_Owen  | SellerG_P  | SellerG_PRD  | SellerG_Pagan  | SellerG_Parkes  | SellerG_Parkinson  | SellerG_Peake  | SellerG_Peter  | SellerG_Philip  | SellerG_Point  | SellerG_Pride  | SellerG_Prime  | SellerG_Private/Tiernan's  | SellerG_Professionals  | SellerG_Property  | SellerG_Propertyau  | SellerG_Prowse  | SellerG_Quinta  | SellerG_R&H  | SellerG_RE  | SellerG_REMAX  | SellerG_RW  | SellerG_Raine&Horne  | SellerG_Re  | SellerG_Reach  | SellerG_Real  | SellerG_Red  | SellerG_Redina  | SellerG_Reed  | SellerG_Reliance  | SellerG_Rendina  | SellerG_Rexhepi  | SellerG_Ristic  | SellerG_Rodney  | SellerG_Roger  | SellerG_Rombotis  | SellerG_Rosin  | SellerG_Ross  | SellerG_Rounds  | SellerG_Ryder  | SellerG_S&L  | SellerG_SN  | SellerG_Sandhurst  | SellerG_Schroeder  | SellerG_Scott  | SellerG_Sell  | SellerG_Smart  | SellerG_Space  | SellerG_Steller  | SellerG_Steveway  | SellerG_Surreal  | SellerG_Sweeney/Advantage  | SellerG_Sweeney/Burnham  | SellerG_T  | SellerG_TRUE  | SellerG_The  | SellerG_Thomas  | SellerG_Tiernan's  | SellerG_Trimson  | SellerG_Triwest  | SellerG_U  | SellerG_Upper  | SellerG_Upside  | SellerG_VICPROP  | SellerG_Veitch  | SellerG_Vic  | SellerG_VicHomes  | SellerG_Victory  | SellerG_W.B.  | SellerG_Walsh  | SellerG_Walshe  | SellerG_Weast  | SellerG_Weda  | SellerG_Weston  | SellerG_Westside  | SellerG_White  | SellerG_Whiting  | SellerG_William  | SellerG_Wilson  | SellerG_Win  | SellerG_Wood  | SellerG_Woodards  | SellerG_Xynergy  | SellerG_Zahn  | SellerG_buyMyplace  | SellerG_hockingstuart/Advantage  | SellerG_hockingstuart/Barry  | SellerG_hockingstuart/Buxton  | SellerG_hockingstuart/Harcourts  | SellerG_hockingstuart/Village  | SellerG_hockingstuart/hockingstuart  | SellerG_iHomes  | SellerG_iOne  | SellerG_iProperty  | SellerG_iSell  | Regionname_Southern Metropolitan  | Regionname_Western Victoria  | CouncilArea_Cardinia Shire Council  | CouncilArea_Casey City Council  | CouncilArea_Darebin City Council  | CouncilArea_Maribyrnong City Council  | CouncilArea_Mitchell Shire Council  | CouncilArea_Moorabool Shire Council  | CouncilArea_Moreland City Council  | CouncilArea_Yarra Ranges Shire Council  |

In [ ]:
#parameter tuning
from sklearn.linear_model import LassoCV

lasso_cv = LassoCV(alphas=[10, 20, 50, 100, 200],
                   cv=5, max_iter=10000)

lasso_cv.fit(X_train, y_train)

LassoCV(alphas=[10, 20, 50, 100, 200], cv=5, max_iter=10000)

In [ ]:
lasso_cv.alpha_

np.int64(100)

In [ ]:
from sklearn.linear_model import Lasso

best_lasso = Lasso(alpha=lasso_cv.alpha_)
best_lasso.fit(X_train, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.961e+12, tolerance: 6.647e+11
  model = cd_fast.enet_coordinate_descent(

Lasso(alpha=np.int64(100))

In [ ]:
best_lasso.score(X_test, y_test)

0.6595463658823354

In [ ]:
best_lasso.score(X_train, y_train)

0.6738518759708201

**Regularization Method: Ridge Regularization(L2)**

In [ ]:
from sklearn.linear_model import Ridge
ridgeModel = Ridge(alpha=50, max_iter=100, tol=0.1)
ridgeModel.fit(X_train, y_train)

Ridge(alpha=50, max_iter=100, tol=0.1)

In [ ]:
ridgeModel.score(X_test, y_test)

0.6523907863758523

In [ ]:
ridgeModel.score(X_train, y_train)

0.6597254044396317

In [ ]:
ridgeModel.coef_

In [ ]:
from sklearn.linear_model import RidgeCV

ridge_cv = RidgeCV(alphas=[0.1, 20, 50, 100, 200], cv=5, scoring='r2')

ridge_cv.fit(X_train, y_train)

RidgeCV(alphas=[0.1, 20, 50, 100, 200], cv=5, scoring='r2')

In [ ]:
ridge_cv.score(X_test, y_test)

0.6590526909932941

In [ ]:
ridge_cv.score(X_train, y_train)

0.6696894097952517

## ElasticNet (L1 + L2)

In [ ]:
from sklearn.linear_model import ElasticNetCV

enet_cv = ElasticNetCV(
    alphas=[0.1, 1, 10, 50, 100],
    l1_ratio=[0.2, 0.5, 0.8],
    cv=5,
    max_iter=5000
)

enet_cv.fit(X_train, y_train)

enet_cv.alpha_, enet_cv.l1_ratio_

(np.float64(0.1), np.float64(0.8))

In [ ]:
from sklearn.linear_model import ElasticNet
best_enet = ElasticNet(
    alpha=enet_cv.alpha_,
    l1_ratio=enet_cv.l1_ratio_,
    max_iter=5000
)

best_enet.fit(X_train, y_train)

ElasticNet(alpha=np.float64(0.1), l1_ratio=np.float64(0.8), max_iter=5000)

In [ ]:
best_enet.score(X_test, y_test)

0.6200658048602625

In [ ]:
best_enet.score(X_train, y_train)

0.6225807375763425

#laptop price prediction dataset

In [ ]:
import pandas as pd
df=pd.read_csv("/content/laptop_prices.csv")
df

,Company,Product,TypeName,Inches,Ram,OS,Weight,Price_euros,Screen,ScreenW,...,RetinaDisplay,CPU_company,CPU_freq,CPU_model,PrimaryStorage,SecondaryStorage,PrimaryStorageType,SecondaryStorageType,GPU_company,GPU_model
0,Apple,MacBook Pro,Ultrabook,13.3,8,macOS,1.37,1339.69,Standard,2560,...,Yes,Intel,2.3,Core i5,128,0,SSD,No,Intel,Iris Plus Graphics 640
1,Apple,Macbook Air,Ultrabook,13.3,8,macOS,1.34,898.94,Standard,1440,...,No,Intel,1.8,Core i5,128,0,Flash Storage,No,Intel,HD Graphics 6000
2,HP,250 G6,Notebook,15.6,8,No OS,1.86,575.00,Full HD,1920,...,No,Intel,2.5,Core i5 7200U,256,0,SSD,No,Intel,HD Graphics 620
3,Apple,MacBook Pro,Ultrabook,15.4,16,macOS,1.83,2537.45,Standard,2880,...,Yes,Intel,2.7,Core i7,512,0,SSD,No,AMD,Radeon Pro 455
4,Apple,MacBook Pro,Ultrabook,13.3,8,macOS,1.37,1803.60,Standard,2560,...,Yes,Intel,3.1,Core i5,256,0,SSD,No,Intel,Iris Plus Graphics 650
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1270,Lenovo,Yoga 500-14ISK,2 in 1 Convertible,14.0,4,Windows 10,1.80,638.00,Full HD,1920,...,No,Intel,2.5,Core i7 6500U,128,0,SSD,No,Intel,HD Graphics 520
1271,Lenovo,Yoga 900-13ISK,2 in 1 Convertible,13.3,16,Windows 10,1.30,1499.00,Quad HD+,3200,...,No,Intel,2.5,Core i7 6500U,512,0,SSD,No,Intel,HD Graphics 520
1272,Lenovo,IdeaPad 100S-14IBR,Notebook,14.0,2,Windows 10,1.50,229.00,Standard,1366,...,No,Intel,1.6,Celeron Dual Core N3050,64,0,Flash Storage,No,Intel,HD Graphics
1273,HP,15-AC110nv (i7-6500U/6GB/1TB/Radeon,Notebook,15.6,6,Windows 10,2.19,764.00,Standard,1366,...,No,Intel,2.5,Core i7 6500U,1024,0,HDD,No,AMD,Radeon R5 M330
1274,Asus,X553SA-XX031T (N3050/4GB/500GB/W10),Notebook,15.6,4,Windows 10,2.20,369.00,Standard,1366,...,No,Intel,1.6,Celeron Dual Core N3050,500,0,HDD,No,Intel,HD Graphics

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1275 entries, 0 to 1274
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Company               1275 non-null   object
 1   Product               1275 non-null   object
 2   TypeName              1275 non-null   object
 3   Inches                1275 non-null   float64
 4   Ram                   1275 non-null   int64
 5   OS                    1275 non-null   object
 6   Weight                1275 non-null   float64
 7   Price_euros           1275 non-null   float64
 8   Screen                1275 non-null   object
 9   ScreenW               1275 non-null   int64
 10  ScreenH               1275 non-null   int64
 11  Touchscreen           1275 non-null   object
 12  IPSpanel              1275 non-null   object
 13  RetinaDisplay         1275 non-null   object
 14  CPU_company           1275 non-null   object
 15  CPU_freq              1275 non-null   float64
 16  CPU_model             1275 non-null   object
 17  PrimaryStorage        1275 non-null   int64
 18  SecondaryStorage      1275 non-null   int64
 19  PrimaryStorageType    1275 non-null   object
 20  SecondaryStorageType  1275 non-null   object
 21  GPU_company           1275 non-null   object
 22  GPU_model             1275 non-null   object
dtypes: float64(4), int64(5), object(14)
memory usage: 229.2+ KB

In [ ]:
df.describe()

,Inches,Ram,Weight,Price_euros,ScreenW,ScreenH,CPU_freq,PrimaryStorage,SecondaryStorage
count,1275.000000,1275.000000,1275.000000,1275.000000,1275.000000,1275.000000,1275.000000,1275.000000,1275.000000
mean,15.022902,8.440784,2.040525,1134.969059,1900.043922,1073.904314,2.302980,444.517647,176.069020
std,1.429470,5.097809,0.669196,700.752504,493.346186,283.883940,0.503846,365.537726,415.960655
min,10.100000,2.000000,0.690000,174.000000,1366.000000,768.000000,0.900000,8.000000,0.000000
25%,14.000000,4.000000,1.500000,609.000000,1920.000000,1080.000000,2.000000,256.000000,0.000000
50%,15.600000,8.000000,2.040000,989.000000,1920.000000,1080.000000,2.500000,256.000000,0.000000
75%,15.600000,8.000000,2.310000,1496.500000,1920.000000,1080.000000,2.700000,512.000000,0.000000
max,18.400000,64.000000,4.700000,6099.000000,3840.000000,2160.000000,3.600000,2048.000000,2048.000000

In [ ]:
df.isnull().sum()

Company                 0
Product                 0
TypeName                0
Inches                  0
Ram                     0
OS                      0
Weight                  0
Price_euros             0
Screen                  0
ScreenW                 0
ScreenH                 0
Touchscreen             0
IPSpanel                0
RetinaDisplay           0
CPU_company             0
CPU_freq                0
CPU_model               0
PrimaryStorage          0
SecondaryStorage        0
PrimaryStorageType      0
SecondaryStorageType    0
GPU_company             0
GPU_model               0
dtype: int64

In [ ]:
df.drop_duplicates(inplace=True)

df.fillna(method='ffill', inplace=True)

/tmp/ipython-input-203905011.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', inplace=True)

In [ ]:
x = df.drop("Price_euros", axis=1)
y = df["Price_euros"]

In [ ]:
num_features = x.select_dtypes(include=["int64", "float64"]).columns
cat_features = x.select_dtypes(include=["object"]).columns
display(num_features)
display(cat_features)

Index(['Inches', 'Ram', 'Weight', 'ScreenW', 'ScreenH', 'CPU_freq',
       'PrimaryStorage', 'SecondaryStorage'],
      dtype='object')

Index(['Company', 'Product', 'TypeName', 'OS', 'Screen', 'Touchscreen',
       'IPSpanel', 'RetinaDisplay', 'CPU_company', 'CPU_model',
       'PrimaryStorageType', 'SecondaryStorageType', 'GPU_company',
       'GPU_model'],
      dtype='object')

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,random_state=2)

In [ ]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [ ]:
model.score(X_test, y_test)

0.6650429542328032

In [ ]:
model.score(X_train, y_train)

0.7022645506892455

In [ ]:
model.coef_
model.intercept_

np.float64(905135.9431057128)

In [ ]:
from sklearn.linear_model import Lasso
lassoModel = Lasso(alpha=100, max_iter=1000, tol=.1)
lassoModel.fit(X_train, y_train)

Lasso(alpha=100, tol=0.1)

In [ ]:
lassoModel.score(X_test, y_test)

0.670305623415753

In [ ]:
lassoModel.score(X_train, y_train)

0.6969503349417481

In [ ]:
lassoModel.coef_

array([ 2.81451591e+05,  4.59258699e+00, -3.95862029e+04, -1.05787708e+05,
        1.39978837e+05,  5.41024191e+04,  1.73152394e+01,  3.45846095e+02,
        1.78661333e+05, -1.69848041e+04,  4.02704089e+05,  1.48060056e+05,
        2.17250683e+05,  1.30594180e+05, -1.94580207e+05,  0.00000000e+00,
        1.92910168e+05, -4.83901871e+04, -3.38845098e+03,  1.80824217e+04,
        0.00000000e+00, -2.17996403e+05, -0.00000000e+00,  3.05439090e+05,
       -1.00755979e+04,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
       -1.97379028e+05,  6.33065978e+04, -6.10850491e+04,  0.00000000e+00,
        0.00000000e+00, -0.00000000e+00, -0.00000000e+00,  8.61461657e+04,
       -7.86454214e+04,  0.00000000e+00,  5.06083483e+05, -0.00000000e+00,
       -0.00000000e+00,  1.13498582e+05,  3.15487937e+04,  3.22389134e+04,
       -0.00000000e+00, -1.46448209e+05, -0.00000000e+00,  0.00000000e+00,
       -0.00000000e+00, -6.70216396e+03,  0.00000000e+00, -0.00000000e+00,
        2.98395676e+04, -0.00000000e+00,  6.64292544e+05,  3.94201552e+04,
        3.99483079e+05,  1.94854502e+04, -0.00000000e+00, -9.34179428e+04,
       -1.20437643e+05,  6.31933626e+04,  0.00000000e+00, -9.83754070e+03,
       -0.00000000e+00,  1.05261826e+04,  0.00000000e+00, -1.19193249e+05,
       -1.56704858e+05,  9.66835432e+03, -0.00000000e+00, -0.00000000e+00,
       -0.00000000e+00,  0.00000000e+00, -0.00000000e+00, -0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00, -0.00000000e+00,
        6.11024133e+04, -0.00000000e+00,  0.00000000e+00, -0.00000000e+00,
        5.09613266e+05,  3.41701161e+05,  0.00000000e+00,  2.02255155e+04,
       -0.00000000e+00, -0.00000000e+00,  1.18524311e+05, -0.00000000e+00,
        1.34034871e+05,  3.21348043e+04,  5.95862538e+04, -0.00000000e+00,
        1.18391809e+05,  0.00000000e+00,  0.00000000e+00,  1.97413932e+05,
        2.25345197e+05, -3.35307574e+04,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00, -0.00000000e+00,
        0.00000000e+00,  0.00000000e+00, -0.00000000e+00,  4.99218451e+03,
       -0.00000000e+00, -9.90864907e+04, -2.70742595e+04,  0.00000000e+00,
        0.00000000e+00, -1.51629279e+05,  0.00000000e+00,  2.50672625e+05,
       -9.63428394e+03, -1.61762446e+05, -6.06806731e+03,  0.00000000e+00,
       -7.50753450e+04, -3.57511474e+05, -4.36127577e+05,  0.00000000e+00,
       -0.00000000e+00, -0.00000000e+00,  1.12329696e+05, -0.00000000e+00,
       -0.00000000e+00,  4.70711844e+05, -0.00000000e+00, -1.56035706e+05,
       -0.00000000e+00, -6.31467552e+03, -0.00000000e+00,  1.88560835e+04,
       -5.28062939e+04,  2.42527115e+04,  0.00000000e+00, -0.00000000e+00,
       -0.00000000e+00, -1.02415804e+05,  3.14010219e+04, -0.00000000e+00,
       -0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
       -3.73092507e+04,  3.83222673e+05, -0.00000000e+00, -1.12799929e+04,
        5.15302354e+04, -0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  3.07572425e+05,  0.00000000e+00, -0.00000000e+00,
        1.90974232e+05, -0.00000000e+00,  7.98256484e+04, -0.00000000e+00,
        0.00000000e+00,  0.00000000e+00, -0.00000000e+00, -0.00000000e+00,
        6.04932887e+04, -0.00000000e+00,  1.41261729e+05,  9.86975418e+01,
        5.47519235e+04, -1.53017557e+05,  1.23547771e+05,  1.19419593e+05,
       -3.93174245e+04, -3.42722622e+04, -2.62500036e+05, -9.38134775e+04,
        0.00000000e+00, -1.70860321e+05, -6.33621765e+03, -0.00000000e+00,
       -1.78616895e+05,  0.00000000e+00,  6.04025938e+04, -0.00000000e+00,
       -8.95063067e+04, -0.00000000e+00, -2.99086489e+05, -0.00000000e+00,
        0.00000000e+00, -3.33748466e+04, -1.89387628e+05,  5.12274110e+04,
       -5.61731729e+04, -1.83606478e+05, -5.73670708e+03, -9.99866837e+04,
        5.01542684e+04,  4.65973634e+05, -0.00000000e+00, -2.67636557e+05,
       -4.07445253e+04, -2.76286374e+02,  5.80939374e+04,  2.12314856e+05,
        7.31104534e+03, -3.79618844e+03, -1.34306660e+05,  3.50196922e+04,
       -2.87289418e+05, -4.98635845e+05,  1.12306666e+05,  8.40132733e+03,
        7.25470223e+04,  2.02815900e+04, -0.00000000e+00,  0.00000000e+00,
        5.72289567e+05,  0.00000000e+00, -0.00000000e+00,  0.00000000e+00,
       -0.00000000e+00,  0.00000000e+00,  0.00000000e+00, -0.00000000e+00,
       -0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  9.59589389e+03,
        0.00000000e+00, -0.00000000e+00, -0.00000000e+00, -1.39031581e+04,
        4.31842329e+01,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
       -0.00000000e+00, -0.00000000e+00, -7.53394583e+03,  4.94615855e+04,
        0.00000000e+00, -9.47136211e+03, -0.00000000e+00,  0.00000000e+00,
       -0.00000000e+00,  0.00000000e+00,  1.92694338e+05, -0.00000000e+00,
        3.19186180e+05,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
       -0.00000000e+00,  0.00000000e+00,  0.00000000e+00, -6.24919542e+03,
        0.00000000e+00, -0.00000000e+00,  2.77398201e+05, -0.00000000e+00,
       -0.00000000e+00,  0.00000000e+00, -0.00000000e+00, -0.00000000e+00,
        0.00000000e+00,  7.27843336e+04, -0.00000000e+00, -0.00000000e+00,
       -5.86656010e+04, -0.00000000e+00, -0.00000000e+00,  0.00000000e+00,
        7.08521334e+03,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
       -0.00000000e+00, -0.00000000e+00, -0.00000000e+00,  0.00000000e+00,
       -0.00000000e+00,  0.00000000e+00, -0.00000000e+00,  0.00000000e+00,
       -0.00000000e+00, -0.00000000e+00, -5.53964799e+04, -0.00000000e+00,
        0.00000000e+00,  3.71491775e+04, -0.00000000e+00, -0.00000000e+00,
        0.00000000e+00, -0.00000000e+00, -0.00000000e+00,  3.61651819e+04,
       -2.67841317e+04, -2.29905349e+04, -4.11713186e+04,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00, -0.00000000e+00,
        0.00000000e+00, -0.00000000e+00, -0.00000000e+00, -0.00000000e+00,
        4.05221601e+04,  0.00000000e+00,  9.86464130e+04,  0.00000000e+00,
       -0.00000000e+00, -0.00000000e+00,  0.00000000e+00,  3.50146816e+05,
        0.00000000e+00, -0.00000000e+00, -1.17284295e+05,  0.00000000e+00,
        0.00000000e+00,  9.05133613e+04,  0.00000000e+00, -0.00000000e+00,
       -1.81567145e+04,  0.00000000e+00, -0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  2.64196683e+05, -0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  2.94753224e+04,  7.59678032e+04, -0.00000000e+00,
        0.00000000e+00, -0.00000000e+00, -0.00000000e+00,  7.10795819e+04,
       -8.40054091e+03, -2.06698239e+05,  3.43270383e+04,  0.00000000e+00,
       -0.00000000e+00, -0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
       -0.00000000e+00,  9.02659672e+04, -3.48810260e+04,  0.00000000e+00,
       -0.00000000e+00, -0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
       -0.00000000e+00, -0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00, -0.00000000e+00,  1.56013914e+05, -0.00000000e+00,
        1.25174616e+05,  0.00000000e+00,  0.00000000e+00, -0.00000000e+00,
       -0.00000000e+00,  0.00000000e+00,  0.00000000e+00, -0.00000000e+00,
       -0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.11075611e+05,
        8.07968173e+03, -4.75647200e+04, -1.65735369e+04, -2.72653112e+04,
       -0.00000000e+00, -0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00, -3.85680484e+04, -4.08706191e+05,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00, -0.00000000e+00,
        7.18804429e+05,  0.00000000e+00, -0.00000000e+00, -9.42017884e+03,
       -1.39067340e+04, -0.00000000e+00,  0.00000000e+00, -1.71935790e+05,
       -0.00000000e+00, -4.55202520e+04,  1.57283545e+04, -0.00000000e+00,
       -0.00000000e+00,  0.00000000e+00,  3.85656501e+04, -0.00000000e+00,
        0.00000000e+00,  0.00000000e+00, -0.00000000e+00,  1.00415010e+05,
        0.00000000e+00, -0.00000000e+00,  0.00000000e+00, -0.00000000e+00,
        0.00000000e+00,  3.97716777e+03,  7.61406627e+04, -0.00000000e+00,
       -0.00000000e+00, -1.72444045e+04, -1.53702700e+04,  0.00000000e+00,
        0.00000000e+00, -5.18813445e+04,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00, -1.72859082e+05,  7.09258573e+04,  2.79159988e+04,
        3.17797280e+04, -3.38170390e+05, -0.00000000e+00,  2.34982899e+05,
        2.33330320e+05, -2.69120482e+04,  0.00000000e+00, -3.97196615e+04,
        3.42377666e+05,  1.02261686e+05, -0.00000000e+00,  1.28697754e+05,
       -2.29223417e+05, -0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
       -0.00000000e+00, -0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
       -0.00000000e+00,  0.00000000e+00,  1.59070531e+05, -9.58205988e+04,
       -0.00000000e+00,  0.00000000e+00,  2.05379481e+05,  9.34683402e+04,
       -1.36684356e+05, -0.00000000e+00,  1.80195918e+04,  0.00000000e+00])

In [ ]:
zero_coeff_features = X_train.columns[lassoModel.coef_ == 0]

print("Features with coefficients converted to 0 by Lasso Regularization:")
for feature in zero_coeff_features:
    print(feature,end="  | ")

Features with coefficients converted to 0 by Lasso Regularization:
Suburb_Ardeer  | Suburb_Attwood  | Suburb_Balaclava  | Suburb_Bayswater  | Suburb_Bayswater North  | Suburb_Beaumaris  | Suburb_Berwick  | Suburb_Blackburn  | Suburb_Blackburn South  | Suburb_Boronia  | Suburb_Briar Hill  | Suburb_Brighton East  | Suburb_Broadmeadows  | Suburb_Brunswick West  | Suburb_Bundoora  | Suburb_Burnley  | Suburb_Burnside Heights  | Suburb_Burwood East  | Suburb_Cairnlea  | Suburb_Campbellfield  | Suburb_Caroline Springs  | Suburb_Caulfield South  | Suburb_Cheltenham  | Suburb_Clyde North  | Suburb_Craigieburn  | Suburb_Cranbourne  | Suburb_Cremorne  | Suburb_Croydon  | Suburb_Croydon North  | Suburb_Dandenong  | Suburb_Dandenong North  | Suburb_Diamond Creek  | Suburb_Dingley Village  | Suburb_Docklands  | Suburb_Doncaster East  | Suburb_Donvale  | Suburb_Doreen  | Suburb_Edithvale  | Suburb_Eltham  | Suburb_Eltham North  | Suburb_Epping  | Suburb_Eumemmerring  | Suburb_Fawkner  | Suburb_Ferntree Gully  | Suburb_Footscray  | Suburb_Forest Hill  | Suburb_Frankston  | Suburb_Frankston North  | Suburb_Frankston South  | Suburb_Gardenvale  | Suburb_Gisborne  | Suburb_Gladstone Park  | Suburb_Glen Huntly  | Suburb_Glen Waverley  | Suburb_Greensborough  | Suburb_Greenvale  | Suburb_Hallam  | Suburb_Healesville  | Suburb_Highett  | Suburb_Hillside  | Suburb_Hoppers Crossing  | Suburb_Huntingdale  | Suburb_Ivanhoe  | Suburb_Jacana  | Suburb_Keilor Downs  | Suburb_Keilor Lodge  | Suburb_Kew East  | Suburb_Keysborough  | Suburb_Kings Park  | Suburb_Kooyong  | Suburb_Lalor  | Suburb_Lower Plenty  | Suburb_Lynbrook  | Suburb_MacLeod  | Suburb_Malvern East  | Suburb_Melton  | Suburb_Melton South  | Suburb_Mentone  | Suburb_Mernda  | Suburb_Mill Park  | Suburb_Mitcham  | Suburb_Montmorency  | Suburb_Moorabbin  | Suburb_Mordialloc  | Suburb_Mount Waverley  | Suburb_Murrumbeena  | Suburb_Newport  | Suburb_North Melbourne  | Suburb_Princes Hill  | Suburb_Ripponlea  | Suburb_Seaholme  | Suburb_South Kingsville  | Suburb_South Yarra  | Suburb_Spotswood  | Suburb_St Kilda  | Suburb_Travancore  | SellerG_AIME  | SellerG_ASL  | SellerG_Airport  | SellerG_Alexkarbon  | SellerG_Allan  | SellerG_Allens  | SellerG_Anderson  | SellerG_Appleby  | SellerG_Ascend  | SellerG_Assisi  | SellerG_Australian  | SellerG_Barlow  | SellerG_Batty  | SellerG_Bayside  | SellerG_Bekdon  | SellerG_Besser  | SellerG_Biggin  | SellerG_Blue  | SellerG_Brace  | SellerG_Brad  | SellerG_Bustin  | SellerG_Buxton/Advantage  | SellerG_Buxton/Find  | SellerG_C21  | SellerG_CASTRAN  | SellerG_Calder  | SellerG_Cayzer  | SellerG_Century  | SellerG_Chambers  | SellerG_Changing  | SellerG_Charlton  | SellerG_Chisholm  | SellerG_Clairmont  | SellerG_Collings  | SellerG_Compton  | SellerG_Considine  | SellerG_Coventry  | SellerG_Craig  | SellerG_Crane  | SellerG_D'Aprano  | SellerG_David  | SellerG_Del  | SellerG_Direct  | SellerG_Dixon  | SellerG_Domain  | SellerG_Edward  | SellerG_Elite  | SellerG_Eview  | SellerG_FN  | SellerG_First  | SellerG_Fletchers  | SellerG_Fletchers/Fletchers  | SellerG_Fletchers/One  | SellerG_Frank  | SellerG_GL  | SellerG_Galldon  | SellerG_Gardiner  | SellerG_Garvey  | SellerG_Geoff  | SellerG_Grantham  | SellerG_Gunn&Co  | SellerG_HAR  | SellerG_Hall  | SellerG_Ham  | SellerG_Hamilton  | SellerG_Holland  | SellerG_Homes  | SellerG_Hooper  | SellerG_Hoskins  | SellerG_Hunter  | SellerG_Icon  | SellerG_Iconek  | SellerG_J  | SellerG_JMRE  | SellerG_Jason  | SellerG_Joe  | SellerG_Johnston  | SellerG_Joseph  | SellerG_Karen  | SellerG_Kelly  | SellerG_Ken  | SellerG_LJ  | SellerG_Leased  | SellerG_Love  | SellerG_Lucas  | SellerG_Luxton  | SellerG_MICM  | SellerG_Maddison  | SellerG_Mandy  | SellerG_Mason  | SellerG_Matthew  | SellerG_Max  | SellerG_McLennan  | SellerG_Meadows  | SellerG_Melbourne  | SellerG_Metro  | SellerG_Naison  | SellerG_Nardella  | SellerG_Nelson  | SellerG_New  | SellerG_Nguyen  | SellerG_Nicholson  | SellerG_North  | SellerG_O'Brien  | SellerG_O'Donoghues  | SellerG_Oak  | SellerG_One  | SellerG_Oriental  | SellerG_Owen  | SellerG_PRDNationwide  | SellerG_Pagan  | SellerG_Parkes  | SellerG_Parkinson  | SellerG_Peter  | SellerG_Pride  | SellerG_Private/Tiernan's  | SellerG_Prof.  | SellerG_Professionals  | SellerG_Property  | SellerG_Propertyau  | SellerG_Prowse  | SellerG_Purplebricks  | SellerG_R&H  | SellerG_RE  | SellerG_Re  | SellerG_Reach  | SellerG_Real  | SellerG_Red  | SellerG_Redina  | SellerG_Reed  | SellerG_Rosin  | SellerG_Ross  | SellerG_S&L  | SellerG_Scott  | SellerG_Steller  | SellerG_Steveway  | SellerG_Sweeney/Advantage  | SellerG_Thomas  | SellerG_Tiernan's  | SellerG_Triwest  | SellerG_VICPROP  | SellerG_Vic  | SellerG_W.B.  | SellerG_WHITEFOX  | SellerG_Walsh  | SellerG_Walshe  | SellerG_Weda  | SellerG_Weston  | SellerG_White  | SellerG_Whiting  | SellerG_William  | SellerG_Win  | SellerG_Wood  | SellerG_Zahn  | SellerG_buyMyplace  | SellerG_hockingstuart/Advantage  | SellerG_hockingstuart/Barry  | SellerG_hockingstuart/Buxton  | SellerG_hockingstuart/Village  | SellerG_iOne  | SellerG_iTRAK  | Regionname_Eastern Victoria  | Regionname_Western Victoria  | CouncilArea_Casey City Council  | CouncilArea_Greater Dandenong City Council  | CouncilArea_Kingston City Council  | CouncilArea_Knox City Council  | CouncilArea_Macedon Ranges Shire Council  | CouncilArea_Manningham City Council  | CouncilArea_Maribyrnong City Council  | CouncilArea_Maroondah City Council  | CouncilArea_Melbourne City Council  | CouncilArea_Melton City Council  | CouncilArea_Monash City Council  | CouncilArea_Nillumbik Shire Council  | CouncilArea_Port Phillip City Council  | CouncilArea_Wyndham City Council  | CouncilArea_Yarra Ranges Shire Council  |

In [ ]:
from sklearn.linear_model import LassoCV

lasso_cv = LassoCV(alphas=[10, 20, 50, 100, 200],
                   cv=5, max_iter=10000)

lasso_cv.fit(X_train, y_train)

LassoCV(alphas=[10, 20, 50, 100, 200], cv=5, max_iter=10000)

In [ ]:
lasso_cv.alpha_

np.int64(200)

In [ ]:
from sklearn.linear_model import Lasso

best_lasso = Lasso(alpha=lasso_cv.alpha_)
best_lasso.fit(X_train, y_train)

Lasso(alpha=np.int64(200))

In [ ]:
best_lasso.score(X_test, y_test)

0.6700945992433417

In [ ]:
best_lasso.score(X_train, y_train)

0.693721749224107

In [ ]:
from sklearn.linear_model import Ridge
ridgeModel = Ridge(alpha=50, max_iter=100, tol=0.1)
ridgeModel.fit(X_train, y_train)

Ridge(alpha=50, max_iter=100, tol=0.1)

In [ ]:
ridgeModel.score(X_test, y_test)

0.6663790505621653

In [ ]:
ridgeModel.score(X_train, y_train)

0.6783203974322243

In [ ]:
ridgeModel.coef_

array([ 2.87859584e+05, -6.52049002e-01, -4.42711624e+04, -1.03191595e+05,
        1.46185681e+05,  5.13144209e+04,  1.60814488e+01,  3.86950854e+02,
        5.95703485e+04, -1.09980546e+04,  1.44229513e+05,  5.05036398e+04,
        6.70429398e+04,  6.29998578e+04, -1.11677737e+05, -5.43267175e+01,
        6.09812069e+04, -4.44730480e+04, -3.71520581e+04, -1.37598793e+04,
        0.00000000e+00, -1.16157068e+05, -2.93614880e+04,  1.61158369e+05,
       -4.24420558e+04,  4.70591849e+03,  1.02829097e+04,  3.54056496e+03,
       -3.27381758e+04,  5.03040493e+04, -2.88509742e+04,  5.29263363e+03,
        8.35724215e+03, -3.43915286e+03,  5.12371853e+02,  7.90065138e+04,
       -4.66777373e+04,  0.00000000e+00,  3.00827695e+05, -7.36052780e+04,
       -3.78593583e+03,  2.78996087e+04,  2.85749208e+04,  4.37643502e+03,
       -2.39206432e+04, -6.03062650e+04, -5.78698181e+03, -1.98151827e+03,
       -7.36884217e+03, -3.88977494e+04,  1.41253413e+03, -6.05724101e+02,
        5.06109964e+02, -2.37622037e+04,  2.52890496e+05,  6.84028427e+03,
        1.51897525e+05,  1.57944744e+04, -5.82359942e+03, -3.98918124e+04,
       -2.96451661e+04,  2.91197591e+04, -5.31423617e+03, -3.62920314e+04,
       -9.26621713e+03, -2.93375434e+03,  1.27629664e+04, -7.88734614e+04,
       -9.27981052e+04, -1.04473444e+04, -1.04954230e+04, -2.60126842e+02,
       -1.91921880e+04,  1.24014761e+04, -7.33778071e+02, -2.81392341e+02,
        4.89651909e+03,  5.37222315e+03,  0.00000000e+00, -1.66238607e+04,
        9.31688792e+04, -5.73748804e+02,  1.64547293e+04, -1.66945032e+03,
        1.16672338e+05,  9.59376567e+04,  1.31253815e+04,  3.14523497e+03,
       -2.04267728e+02, -6.76091605e+03,  2.65567049e+04, -1.05205790e+04,
        1.09282472e+05,  1.37923539e+04,  2.22033040e+04,  1.75219406e+03,
        4.29650331e+04, -5.76871968e+04,  1.27725996e+04,  7.28773190e+04,
        9.84274744e+04, -3.88679272e+04, -8.40069443e+03,  4.56536293e+03,
        3.34406102e+04,  1.05355925e+04,  0.00000000e+00, -4.52505862e+03,
        1.29399870e+04, -1.11255037e+03, -1.76141572e+04, -5.80082476e+03,
        2.80359282e+03, -5.58817603e+04, -4.70849805e+04,  4.39119247e+03,
        3.66600844e+03, -7.68172064e+04,  0.00000000e+00,  9.66925111e+04,
       -6.04316900e+04, -1.44475971e+05, -3.88123246e+04,  1.45981812e+04,
       -2.20919688e+04, -1.60288227e+05, -1.91114296e+05,  0.00000000e+00,
       -6.38263549e+03, -3.44503736e+03,  2.86167182e+04, -1.02403251e+04,
        2.13591031e+04,  1.37122406e+05, -2.91518106e+04, -5.11784423e+04,
       -4.25739724e+03, -1.51747056e+04, -2.64271519e+03,  1.15341877e+04,
       -6.16055154e+04, -6.65435360e+02, -2.68546663e+04,  4.40751252e+03,
       -1.57065116e+03, -3.52187905e+04,  1.09179264e+04, -7.36022209e+03,
       -1.18930738e+04,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
       -3.73057999e+04,  1.53121080e+05, -3.24055532e+04, -2.94284634e+04,
        4.88054929e+04,  4.79828200e+03,  0.00000000e+00,  1.06385725e+04,
        0.00000000e+00,  6.12651189e+04,  0.00000000e+00, -3.45658569e+02,
        1.11199502e+05, -2.43798663e+03,  4.95642938e+04, -3.10021612e+04,
        4.69270447e+03,  2.08495679e+04, -1.81723703e+04, -8.69586528e+03,
        3.66011400e+04, -2.08470324e+04,  1.09567348e+05, -1.72673197e+02,
        1.23654931e+04, -3.61721718e+04,  6.17402168e+04,  4.44457900e+04,
       -3.19406067e+04, -8.25492377e+04, -2.12789642e+05, -4.09054691e+04,
        6.66864894e+03, -6.64599097e+04,  4.30567890e+03, -1.51544653e+04,
       -6.62726756e+04,  3.84537526e+03,  1.97412250e+04, -1.23292648e+04,
       -1.07944678e+05, -2.33865513e+04, -1.39048330e+05, -2.08856221e+04,
       -4.22556493e+04, -2.95226300e+04, -3.26779315e+04,  2.77424354e+04,
       -4.02049080e+04, -1.01830994e+05, -3.99917877e+04, -2.77390373e+04,
        3.68280770e+04,  2.29499722e+05, -4.96447079e+03, -8.44793030e+04,
       -2.49482957e+04, -1.86853228e+04,  1.08971555e+04,  1.17348373e+05,
        1.69793570e+03, -5.11286336e+04, -5.35039485e+04,  1.85958559e+04,
       -2.60818820e+05, -4.65605004e+05,  1.04798542e+05,  8.35681936e+03,
        5.95150124e+04,  1.90593379e+04, -3.63815898e+03,  2.51532619e+03,
        1.52281552e+05,  0.00000000e+00, -1.61016823e+04,  0.00000000e+00,
       -7.83741940e+03,  6.41275904e+03,  0.00000000e+00, -7.34424227e+03,
       -6.96940986e+03,  0.00000000e+00,  1.49498301e+04, -2.96133278e+04,
        4.69945580e+03, -1.27584699e+03, -1.19628736e+04, -3.71260261e+04,
       -3.11592454e+03, -7.97687242e+02, -2.59634656e+04,  1.48165351e+04,
       -1.44026024e+04, -3.05329130e+04, -2.99642025e+04,  1.85750756e+04,
        0.00000000e+00, -2.25830543e+04, -3.04730500e+03,  6.03240728e+03,
       -6.19279827e+03,  0.00000000e+00,  7.96847829e+04, -3.99581480e+03,
        6.60903515e+04, -1.36504985e+04, -1.32108399e+03,  1.42791993e+04,
       -7.41397732e+03,  6.61330954e+03, -3.71965973e+03, -1.91877596e+04,
        4.46124938e+03, -5.97458619e+03,  1.06466753e+05, -5.85788490e+03,
       -2.08206983e+04,  0.00000000e+00,  2.55467302e+03, -4.81486392e+03,
       -8.45238081e+02,  1.14832478e+04, -6.11249093e+03, -4.29929987e+03,
       -4.29309652e+04, -6.75774425e+03, -1.40050274e+04,  5.23859882e+03,
       -7.36445478e+03, -9.61683529e+03,  1.33564820e+03, -1.14250574e+04,
       -1.40568015e+04, -9.20838978e+03, -1.31835481e+04,  0.00000000e+00,
       -1.46149647e+03, -2.37354287e+03, -5.97068826e+03,  2.78144284e+02,
       -7.33778071e+02, -2.47051619e+03, -6.36356095e+04, -5.74782376e+03,
        1.97392032e+03,  1.36550642e+04, -7.12472086e+03, -9.86795906e+03,
        0.00000000e+00, -3.56563847e+03, -1.40510382e+04,  1.57188285e+04,
       -1.67561378e+04, -4.12529039e+04, -3.29061737e+04,  5.98510398e+03,
       -1.57407268e+03,  0.00000000e+00,  0.00000000e+00, -9.06444292e+03,
        1.39322049e+03, -5.87754799e+03, -1.39822646e+04, -5.84175365e+03,
        1.11796635e+04,  9.43540473e+03,  7.77303481e+04,  1.23003836e+03,
       -1.09766628e+04, -3.84117384e+02,  0.00000000e+00,  2.08904766e+05,
        1.41511086e+04, -3.19459021e+03, -6.57605392e+04, -1.13281196e+02,
        2.50110018e+03,  2.80942386e+04, -1.25301956e+04, -1.74986904e+03,
       -1.37794143e+04,  0.00000000e+00, -2.25035934e+04,  0.00000000e+00,
        0.00000000e+00,  2.24565099e+05, -6.28924459e+03,  7.20512427e+03,
        0.00000000e+00,  1.72476638e+04,  4.69629767e+04, -2.81392341e+02,
        2.79583225e+03, -1.05600162e+04, -5.82359942e+03,  4.87305025e+04,
       -4.47415441e+04, -3.41211046e+04,  1.08667843e+04,  0.00000000e+00,
       -4.93090404e+03, -1.86061201e+04, -5.87645068e+02, -9.01550010e+02,
       -2.94559403e+03,  6.36034403e+04, -3.94434144e+04,  3.09554167e+03,
        8.64359139e+03, -1.45417660e+04,  3.20118714e+03,  4.99287841e+02,
       -1.64449853e+03, -1.17233078e+04,  6.59848824e+03, -1.45154734e+02,
        2.20490899e+03, -2.98413860e+03,  4.18344113e+04, -1.63529240e+04,
        4.08464422e+04, -1.48452456e+02,  0.00000000e+00, -4.73760367e+03,
       -3.63418965e+03,  1.21099745e+04,  0.00000000e+00, -1.12058469e+04,
       -9.56000117e+03,  8.51755948e+03,  3.28716910e+03,  7.85855269e+04,
        9.17422813e+03, -4.60243719e+04, -1.68855461e+04, -5.19408424e+04,
       -8.80874656e+03, -1.14408191e+04,  1.07134681e+04,  1.55364776e+04,
        0.00000000e+00,  0.00000000e+00, -3.89680496e+04, -8.43954968e+04,
        3.62497188e+03,  1.07044509e+03,  4.17394336e+03, -1.95550420e+03,
        9.53146219e+04,  0.00000000e+00, -3.71119122e+03, -3.92697522e+04,
       -3.28351780e+04, -5.34881101e+02,  0.00000000e+00, -7.54848563e+04,
       -8.68834810e+03, -2.86753384e+04,  1.05832485e+04, -3.44503736e+03,
       -7.13501216e+03,  0.00000000e+00,  1.49554195e+04, -5.17016231e+03,
        6.41590650e+03,  5.92211381e+03, -9.15922293e+03,  1.62799113e+04,
        1.02263960e+04, -5.42375165e+03,  7.43678606e+03, -1.33125756e+04,
       -2.10392588e+04, -4.71697157e+03,  1.65569233e+04, -1.53191368e+03,
       -3.20092220e+03, -2.40182018e+04, -4.21641829e+04,  0.00000000e+00,
        0.00000000e+00, -7.19352561e+04,  2.93931721e+03,  3.29128081e+03,
        1.07669949e+03,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        2.85911925e+04, -9.58574187e+04,  3.12409410e+04,  3.62398034e+04,
        1.78642496e+05, -1.77776886e+05,  4.79828200e+03,  2.57757586e+05,
        1.89559353e+05, -1.06222628e+05,  1.95476672e+04, -5.78523384e+04,
        4.39762027e+04,  1.60899595e+04,  9.02263927e+03,  3.23030527e+04,
       -1.22329112e+05, -3.87176745e+04,  1.79908900e+04,  1.29399870e+04,
        2.10045574e+04, -9.12430106e+04,  2.19506077e+04, -2.41045497e+04,
       -8.39415959e+03, -3.45546131e+04,  5.22207093e+04, -1.04439040e+05,
        3.70277283e+03, -1.37935774e+04,  1.91046591e+05,  8.95568416e+04,
       -2.24136528e+04, -3.44503736e+03,  5.32379772e+03,  1.45981812e+04])

In [ ]:
from sklearn.linear_model import RidgeCV

ridge_cv = RidgeCV(alphas=[0.1, 20, 50, 100, 200], cv=5, scoring='r2')

ridge_cv.fit(X_train, y_train)

RidgeCV(alphas=[0.1, 20, 50, 100, 200], cv=5, scoring='r2')

In [ ]:
ridge_cv.score(X_test, y_test)

0.666098676728587

In [ ]:
ridge_cv.score(X_train, y_train)

0.7022303709847729

In [ ]:
from sklearn.linear_model import ElasticNetCV

enet_cv = ElasticNetCV(
    alphas=[0.1, 1, 10, 50, 100],
    l1_ratio=[0.2, 0.5, 0.8],
    cv=5,
    max_iter=5000
)

enet_cv.fit(X_train, y_train)

enet_cv.alpha_, enet_cv.l1_ratio_

(np.float64(0.1), np.float64(0.8))

In [ ]:
from sklearn.linear_model import ElasticNet
best_enet = ElasticNet(
    alpha=enet_cv.alpha_,
    l1_ratio=enet_cv.l1_ratio_,
    max_iter=5000
)

best_enet.fit(X_train, y_train)

ElasticNet(alpha=np.float64(0.1), l1_ratio=np.float64(0.8), max_iter=5000)

In [ ]:
best_enet.score(X_test, y_test)

0.6518875603503678

In [ ]:
best_enet.score(X_train, y_train)

0.6555849160191883