#decision making dataset practice

In [ ]:
import pandas as pd
df=pd.read_csv("/content/loan_dataset.csv")
df

,Age,Income,Employment,CreditScore,LoanAmount,MaritalStatus,Loan
0,60,24686,Employed,634,26990,Married,Rejected
1,50,30306,Self-employed,334,18753,Married,Rejected
2,34,96215,Self-employed,772,5277,Single,Sanctioned
3,64,58264,Employed,775,7835,Single,Sanctioned
4,29,71607,Self-employed,363,32302,Married,Rejected
...,...,...,...,...,...,...,...
995,53,75861,Employed,631,48131,Single,Rejected
996,22,36752,Employed,826,54359,Divorced,Rejected
997,34,138604,Employed,594,11170,Divorced,Rejected
998,61,18690,Self-employed,370,18053,Divorced,Rejected
999,60,93285,Employed,634,42478,Married,Rejected

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Age            1000 non-null   int64
 1   Income         1000 non-null   int64
 2   Employment     1000 non-null   object
 3   CreditScore    1000 non-null   int64
 4   LoanAmount     1000 non-null   int64
 5   MaritalStatus  1000 non-null   object
 6   Loan           1000 non-null   object
dtypes: int64(4), object(3)
memory usage: 54.8+ KB

In [ ]:
df.describe()

               Age         Income  CreditScore    LoanAmount
count  1000.000000    1000.000000  1000.000000   1000.000000
mean     42.513000   84896.831000   576.580000  26414.289000
std      12.630573   37963.485543   159.703315  14151.457469
min      21.000000   18571.000000   300.000000   1950.000000
25%      31.000000   51724.000000   436.000000  14252.250000
50%      43.000000   84704.000000   580.500000  26512.500000
75%      54.000000  117711.500000   715.000000  38264.500000
max      65.000000  163876.000000   850.000000  56543.000000

In [ ]:
df.isnull().sum()

Age              0
Income           0
Employment       0
CreditScore      0
LoanAmount       0
MaritalStatus    0
Loan             0
dtype: int64

In [ ]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df["Employment"]=le.fit_transform(df["Employment"])
df["MaritalStatus"]=le.fit_transform(df["MaritalStatus"])

In [ ]:
feature=df.drop(columns=["Loan"],axis=1)
target=df["Loan"]

In [ ]:
from sklearn.model_selection import train_test_split
feature_train,feature_test,target_train,target_test=train_test_split(feature,target,test_size=0.2,random_state=42)

In [ ]:
df.describe()

,Age,Income,Employment,CreditScore,LoanAmount,MaritalStatus
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,42.513000,84896.831000,0.578000,576.580000,26414.289000,1.217000
std,12.630573,37963.485543,0.708815,159.703315,14151.457469,0.674066
min,21.000000,18571.000000,0.000000,300.000000,1950.000000,0.000000
25%,31.000000,51724.000000,0.000000,436.000000,14252.250000,1.000000
50%,43.000000,84704.000000,0.000000,580.500000,26512.500000,1.000000
75%,54.000000,117711.500000,1.000000,715.000000,38264.500000,2.000000
max,65.000000,163876.000000,2.000000,850.000000,56543.000000,2.000000

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
feature_train=sc.fit_transform(feature_train)
feature_test

     Age  Income  Employment  CreditScore  LoanAmount  MaritalStatus
521   56  141227           0          782       41205              1
737   33   82608           1          703       42994              1
740   60  104699           0          791       26520              1
660   37  109456           0          785       17791              1
411   47  157231           1          596       35700              2
..   ...     ...         ...          ...         ...            ...
408   48   45298           2          608       22923              0
332   42  142726           0          578       47318              1
208   27   20168           1          684       11798              1
613   32   85599           0          322       17343              1
78    37  102616           0          762       20074              1

[200 rows x 6 columns]

In [ ]:
feature_test=sc.fit_transform(feature_test)
feature_test

array([[ 1.18160959,  1.52993185, -0.8106453 ,  1.32511533,  0.9271951 ,
        -0.23735633],
       [-0.68622687, -0.02705652,  0.62412514,  0.82436619,  1.05278278,
        -0.23735633],
       [ 1.50645071,  0.55970596, -0.8106453 ,  1.3821627 , -0.10369092,
        -0.23735633],
       ...,
       [-1.17348856, -1.68553507,  0.62412514,  0.70393285, -1.13717433,
        -0.23735633],
       [-0.76743715,  0.05238789, -0.8106453 , -1.59063914, -0.7479157 ,
        -0.23735633],
       [-0.36138575,  0.50437908, -0.8106453 ,  1.19834339, -0.55619969,
        -0.23735633]])

In [ ]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier(max_depth=4,min_samples_split=5)
model.fit(feature_train,target_train)

DecisionTreeClassifier(max_depth=4, min_samples_split=5)

In [ ]:
predic=model.predict(feature_test)
predic=pd.DataFrame(predic,columns=["Predicted"],index=target_test.index)
predic

      Predicted
521  Sanctioned
737  Sanctioned
740  Sanctioned
660  Sanctioned
411    Rejected
..          ...
408    Rejected
332    Rejected
208    Rejected
613    Rejected
78   Sanctioned

[200 rows x 1 columns]

In [ ]:
from sklearn.metrics import accuracy_score, classification_report
accuracy=accuracy_score(target_test,predic)
print(accuracy)

print(classification_report(target_test,predic))

0.895
              precision    recall  f1-score   support

    Rejected       0.96      0.90      0.93       149
  Sanctioned       0.75      0.88      0.81        51

    accuracy                           0.90       200
   macro avg       0.85      0.89      0.87       200
weighted avg       0.90      0.90      0.90       200

In [ ]:
predic.value_counts()

Predicted
Rejected      140
Sanctioned     60
Name: count, dtype: int64

In [ ]:
merged=pd.concat((target_test,predic),axis=1)
merged

           Loan   Predicted
521  Sanctioned  Sanctioned
737    Rejected  Sanctioned
740  Sanctioned  Sanctioned
660  Sanctioned  Sanctioned
411    Rejected    Rejected
..          ...         ...
408    Rejected    Rejected
332    Rejected    Rejected
208    Rejected    Rejected
613    Rejected    Rejected
78   Sanctioned  Sanctioned

[200 rows x 2 columns]

In [ ]:
merged_sorted = merged.sort_values(by=['Loan', 'Predicted']).reset_index(drop=True)  #with sorted prediction just for knowledge
display(merged_sorted)

           Loan   Predicted
0      Rejected    Rejected
1      Rejected    Rejected
2      Rejected    Rejected
3      Rejected    Rejected
4      Rejected    Rejected
..          ...         ...
195  Sanctioned  Sanctioned
196  Sanctioned  Sanctioned
197  Sanctioned  Sanctioned
198  Sanctioned  Sanctioned
199  Sanctioned  Sanctioned

[200 rows x 2 columns]